on: 
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-workflow:
    strategy:
      matrix:
        kubebuilder-version:
          - 2.3.1
          - 3.0.0
          - master
        kubebuilder-only:
          - true
          - false
        etcd-version:
          - 
          - v3.4.15
        kubernetes-version:
          - 
          - v1.19.10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test the workflow
      uses: ./
      with:
        version: ${{ matrix.kubebuilder-version }}
        kubebuilderOnly: ${{ matrix.kubebuilder-only }}
        etcdVersion: ${{ matrix.etcd-version }}
        kubernetesVersion: ${{ matrix.kubernetes-version }}
    - name: Check the existence of kubebuilder
      env:
        KUBEBUILDER_ONLY: ${{ matrix.kubebuilder-only }}
      run: |-
        cd /usr/local/kubebuilder/bin
        if [ -f "./kubebuilder" ] && [ "$KUBEBUILDER_ONLY" == "true" ]; then
          if [ ! -f "./kubectl" ] && [ ! -f "./kube-apiserver" ] && [ ! -f "./etcd" ]; then
            echo "Only kubebuilder have been installed!"
            echo "Checking if the binaries are executable"
            ./kubebuilder version
            exit 0
          else
            echo "There are extra binaries installed"
            ls -la ./
            exit 1
          fi
        fi
        if [ -f "./kubectl" ] && [ -f "./kube-apiserver" ] && [ -f "./etcd" ] && [ -f "./kubebuilder" ]; then
          echo "All binaries from kubebuilder have been installed!"
          echo "Checking if the binaries are executable"
          ./kubebuilder version
          ./kubectl version --client true
          ./kube-apiserver --version
          ./etcd --version
        else
          echo "Cannot find the binaries from kubuilder!"
          ls -la ./
          exit 1
        fi
